FROM node:alpine3.14 as build
WORKDIR /app
COPY package.json package.json
RUN npm install --force --legacy-peer-deps
COPY . .
RUN npm run build:prod

FROM nginx:stable-alpine
COPY ./dockers/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/ims-ui/ /usr/share/nginx/html